---
- name: install support software packages
  apt:
    pkg: "{{ item }}"
    state: installed
  become: yes
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - python-software-properties
  tags:
    - ansible
    - packages

- name: Ensure ansible apt repository is installed
  apt_repository:
    repo: "ppa:ansible/ansible"
    update_cache: yes

- name: Ensure ansible is installed
  apt:
    pkg: ansible
    state: installed
