---
# Installation of supporting packages used by ansible on an instance.
- name: install support software packages
  apt:
    pkg={{ item }}
    state=installed
  sudo: yes
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - python-software-properties
  tags:
    - ansible
    - packages

- name: Ensure ansible apt repository is installed
  apt_repository:
    repo='ppa:ansible/ansible'
    update_cache=yes

- name: Ensure ansible is installed
  apt:
    pkg=ansible
    state=installed

- name: install support python packages
  pip: name={{ item }}
  with_items:
    - python-keyczar
    - boto
  tags:
    - ansible
    - packages

- name: create /opt/etc/ansible directory
  file:
    path=/opt/etc/ansible
    state=directory
    mode=755
  tags:
    - ansible
    - inventory

- name: create ec2.py file
  get_url:
    dest=/opt/etc/ansible
    url="https://raw.githubusercontent.com/ansible/ansible/devel/plugins/inventory/ec2.py"
    mode=755
  tags:
    - ansible
    - inventory

- name: create ec2.ini file
  copy:
    src=ec2.ini
    dest=/opt/etc/ansible/ec2.ini
    mode=644
  tags:
    - ansible
    - inventory

- name: Update temporay directory location
  lineinfile:
    dest=/etc/ansible/ansible.cfg
    regexp=^remote_tmp
    line="remote_tmp     = {{ ansible_remote_tmp }}"
  when: ansible_remote_tmp is defined and ansible_remote_tmp|length > 0
