---
# Installation of supporting packages used by ansible on an instance.
- import_tasks: install_via_apt.yml
  when: ansible_pkg_mgr == "apt"

- import_tasks: install_via_yum.yml
  when: ansible_pkg_mgr == "yum"

- name: install support python packages
  pip:
    name: "{{ item }}"
  with_items:
    - python-keyczar
    - boto
  tags:
    - ansible
    - packages

- name: create /opt/etc/ansible directory
  file:
    path: /opt/etc/ansible
    state: directory
    mode: 0755
  tags:
    - ansible
    - inventory

- name: create ec2.py file
  get_url:
    dest: /opt/etc/ansible
    url: "{{ ansible_ec2_py_url }}"
    mode: 0755
  tags:
    - ansible
    - inventory

- name: create ec2.ini file
  copy:
    src: ec2.ini
    dest: /opt/etc/ansible/ec2.ini
    mode: 0644
  tags:
    - ansible
    - inventory

- name: ensure password file exists if given
  copy:
    content: "{{ ansible_pass }}"
    dest: "{{ ansible_pass_location }}"
    mode: 0644
  when: ansible_pass is defined

- name: Update temporay directory location
  lineinfile:
    dest: /etc/ansible/ansible.cfg
    regexp: ^remote_tmp
    line: "remote_tmp     = {{ ansible_remote_tmp|default('/tmp') }}"
