---
# Installation of supporting packages used by ansible on an instance.
- name: install support software packages
  apt:
    pkg={{ item }}
    state=installed
  sudo: yes
  with_items:
    - build-essential
    - python-dev
    - python-pip
  tags:
    - ansible
    - packages

# Install setup tools to be able to install ansible via pip
- name: retrieve ez_setup.py
  get_url:
    dest=/tmp/ez_setup.py
    url="https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py"
  tags:
    - ansible
    - packages

- name: execute ez_setup.py
  shell: python /tmp/ez_setup.py
  tags:
    - ansible
    - packages

- name: install support python packages
  pip: name={{ item }}
  with_items:
    - ansible
    - python-keyczar
    - boto
  tags:
    - ansible
    - packages

- name: create /opt/etc/ansible directory
  file:
    path=/opt/etc/ansible
    state=directory
    mode=755
  tags:
    - ansible
    - configuration

- name: create ec2.py file
  get_url:
    dest=/opt/etc/ansible
    url="https://raw.githubusercontent.com/ansible/ansible/devel/plugins/inventory/ec2.py"
    mode=755
  tags:
    - ansible
    - configuration

- name: create ec2.ini file
  copy:
    src=ec2.ini
    dest=/opt/etc/ansible/ec2.ini
    mode=644
  tags:
    - ansible
    - configuration
